# SetupTools (setup databases for other tools) 
SETUP_TOOLS_DIR: /home/MCB/jkoszucki/phagedb/others/MGG_DATABASE_SETUP 

# PROPHAGES params
PROPHAGES:
  INPUT_DIR: test # bacterial genome per file
  OUTPUT_DIR: .
  EXTENSION: fasta # input files extension
  CHECKV_CONFIDENCE_TRESHOLD: 95 # prophage extraction
