# SetupTools (setup databases & tools) 
SETUP_TOOLS_DIR: path/to/download_database

# PROPHAGES params
GENBANK_FILE: test.gb # one bacterial genome per file (fasta & gb)
OUTPUT_DIR: path/to/output_directory  # output directory
PRIMARY_EXTEND: 2000 # number of base pairs to extend primary prophage detections
