# SetupTools (setup databases for other tools) 
SETUP_TOOLS_DIR: /home/MCB/jkoszucki/phagedb/others/MGG_DATABASE_SETUP 

# PROPHAGES params
GENBANK_FILE: test # one bacterial genome per file (fasta & gb)
OUTPUT_DIR: . # output directory
CHECKV_CONFIDENCE_TRESHOLD: 95 # prophage extraction
