# SetupTools (setup databases & tools)
SETUP_TOOLS_DIR: /home/MCB/jkoszucki/storage/phageDB/MGG_PROPHAGES_DEPENDENCIES

# PROPHAGES params
GENBANK_FILE: test.gb # annotated bacteria
OUTPUT_DIR: ./prophages_test # output directory
PROPHAGEID_PREFIX: 'TEST' # prophage dataset suffix to be added (can be empty)
PRIMARY_EXTEND: 2000 # number of base pairs to extend primary prophage detections (checkv input)
FINAL_EXTEND: 2000 # number of base pairs to extend final detections
