# SetupTools (setup databases & tools)
SETUP_TOOLS_DIR: /home/MCB/jkoszucki/storage/phageDB/MGG_PROPHAGES_DEPENDENCIES

# PROPHAGES params
GENBANK_FILE: test.gb # one bacterial genome per file (fasta & gb)
OUTPUT_DIR: ./ # output directory
DATE: 1999-01-01
PROPHAGEID_PREFIX: 'KPH' # prophage dataset suffix to be added (can be empty)
PRIMARY_EXTEND: 2000 # number of base pairs to extend primary prophage detections (checkv input)
