# SetupTools (setup databases & tools)
SETUP_TOOLS_DIR: /home/MCB/jkoszucki/storage/jkoszucki/OTHER/MGG_PROPHAGES_DEPENDENCIES 

# PROPHAGES params
GENBANK_FILE: /home/MCB/jkoszucki/storage/dbmgg/databases/bacteria/KLEBPAVIA/KLEBPAVIA_P2/KLEBPAVIA_2023-01/1_BACTERIA_2023-01/bacteria.gb # annotated bacteria
OUTPUT_DIR: /home/MCB/jkoszucki/storage/dbmgg/databases/bacteria/KLEBPAVIA/KLEBPAVIA_P2/KLEBPAVIA_2023-01/2_PROPHAGES_2023-01 # output directory
PROPHAGEID_PREFIX: 'KBVR' # prophage dataset suffix to be added (can be empty)
PRIMARY_EXTEND: 2000 # number of base pairs to extend primary prophage detections (checkv input)
FINAL_EXTEND: 5000 # number of base pairs to extend final detections
